config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact_us" => "static_pages#contact_us"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:destroy, :new, :create]

  namespace :admin do
    root "users#show"
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :categories, only: [:index]
  resources :lessons
  resources :results
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :results
  has_many :word_answers

  validates :content, uniqueness: true

  accepts_nested_attributes_for :word_answers, reject_if:
    lambda {|a| a[:content].blank?}, allow_destroy: true
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < AdminController
  before_action :find_word, only: [:show,:destroy]

  def show
  end

  def edit
  end

  def destroy
    @word.destroy
    redirect_to admin_category_path @category
  end

  private
  def find_word
    @word = Word.find params[:id]
    @category = Category.find params[:category_id]
  end

end

app/views/admin/words/_word.html.erb
<tr>
  <td align="center">
    <%= link_to [:admin, @category, word], method: :delete, data: {confirm: t(".confirm")} do %>
      <em class="glyphicon glyphicon-trash"></em>
    <% end %>
    &nbsp;
    <%= link_to edit_admin_category_word_path(@category, word) do %>
      <em class="glyphicon glyphicon-edit"></em>
    <% end %>
  </td>
  <td>
    <%= link_to admin_category_word_path(@category, word) do %>
      <%= word.content %>
    <% end %>
  </td>
  <td>
    Yes
  </td>
</tr>

app/views/admin/words/show.html.erb
<ul class="breadcrumb">
    <li><a href="#"><%= "Category" %></a></li>
    <li><a href="#"><%= @category.name %></a></li>
    <li class="active">Show</li>
</ul>
<h1>
  <%= @word.content %>
</h1>