config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact_us" => "static_pages#contact_us"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:destroy, :new, :create]

  namespace :admin do
    root "users#show"
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :categories, only: [:index]
  resources :lessons
  resources :results
end

app/views/admin/shared_pages/_navbar.html.erb
<div id="top-nav" class="navbar navbar-inverse navbar-fixed-static">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
        data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong>
        <%= link_to t(".title"), root_path, {class: "navbar-brand"} %>
      </strong>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", role: "button",
              "data-toggle": "dropdown" do %>
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.name %>
            <% end %>
            <ul id="g-account-menu" class="dropdown-menu" role="menu">
              <li>
                <%= link_to t(".my_profile"),
                  admin_user_path(current_user) %>
              </li>
              <li><%= link_to t(".edit_profile"),
                edit_admin_user_path(current_user) %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to logout_path, method: "delete" do %>
              <i class="glyphicon glyphicon-lock"></i>
              <%= t ".log_out" %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to "#" do %>
              <i class="glyphicon glyphicon-user"></i>
              <%= t ".guest" %>
            <% end %>
          </li>
          <li>
            <%= link_to login_path do %>
              <i class="glyphicon glyphicon-lock"></i>
              <%= t ".log_in" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/shared_pages/_sidebar.html.erb
<div class="col-sm-3">
  <% if logged_in? %>
    <%= link_to "#" do %>
      <strong><i class="glyphicon glyphicon-list">
      </i> <%= t ".menu"%> </strong>
    <% end %>
    <hr>
    <ul class="nav nav-stacked">
      <ul class="nav nav-stacked collapse in" id="userMenu">
        <li class="active">
          <%= link_to admin_users_path do %>
            <i class="glyphicon glyphicon-user"></i>
            <%= t ".all_users" %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_categories_path do %>
            <i class="glyphicon glyphicon-th"></i>
            <%= t ".categories" %>
          <% end %>
        </li>
      </ul>
    </ul>
    <hr>
  <% end %>
  <ul class="nav nav-stacked">
    <li> <%= link_to t(".home"), root_path, {title: "Home"} %> </li>
    <li> <%= link_to t(".about"), about_path %> </li>
    <li> <%= link_to t(".help"), help_path %> </li>
    <li> <%= link_to t(".contact"), contact_us_path %> </li>
  </ul>
  <hr>
</div>