config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact_us" => "static_pages#contact_us"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:destroy, :new, :create]

  namespace :admin do
    root "users#show"
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :categories, only: [:index]
  resources :lessons
  resources :results
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
  has_many :words, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  accepts_nested_attributes_for :words, reject_if:
    lambda {|a| a[:content].blank?}, allow_destroy: true

  def start_a_lesson user
    lessons.create user_id: user.id, correct_item: 0, total_item: 3
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :find_category, except: [:index, :new, :create]
  def index
    @categories = Category.order(:name).paginate page: params[:page]
  end

  def new
    @category = Category.new
    @word = @category.words.build
    @word.word_answers.build
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @words = @category.words.paginate page: params[:page]
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to admin_category_path @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t ".success"
    redirect_to admin_categories_path
  end

  private
  def find_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit :name, words_attributes: [:id, :content,
      :_destroy, word_answers_attributes: [:id, :content, :correct, :_destroy] ]
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.paginate page: params[:page]
  end
end

app/views/categories/_category.html.erb
<tr>
  <td align="center">
    <%= form_for (category.lessons.build) do |f| %>
      <%= hidden_field_tag :category, category.id %>
      <%= f.submit t(".save"), class: "btn btn-primary" %>
    <% end %>
  </td>
  <td>
    <%= link_to admin_category_path category do %>
      <%= category.name %>
    <% end %>
  </td>
  <td>
    <%= category.words.count %>
  </td>
</tr>

app/views/categories/index.html.erb
<% provide :title, t(".title") %>
<ul class="breadcrumb">
    <li><%= link_to t(".title"), admin_categories_path %></li>
    <li class="active"><%= t ".current_action" %></li>
</ul>
<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <div class="row">
      <div class="col col-xs-6">
        <h3 class="panel-title"><%= t ".title" %></h3>
      </div>
      <div class="col col-xs-6 text-right">
      <%= button_to "Create New", new_admin_category_path,
        class: "btn btn-sm btn-primary btn-create", method: "get" %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered table-list">
      <thead>
        <tr>
          <th><em class="glyphicon glyphicon-cog"></em></th>
          <th><%= t ".name" %></th>
          <th><%= t ".total_words" %></th>
        </tr>
      </thead>
      <tbody class="categories">
        <%= render @categories %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <%= will_paginate %>
  </div>
</div>