config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact_us" => "static_pages#contact_us"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :users, except: [:destroy, :new, :create]

  namespace :admin do
    root "users#show"
    resources :users
    resources :categories do
      resources :words
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :categories, only: [:index]
  resources :lessons
  resources :results
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessor :remember_token, :activation_token, :reset_token

  has_many :active_relationships,  class_name: Relationship.name,
    foreign_key: :follower_id,
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id,
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities
  has_many :lessons

  validates :name,  presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  before_save :downcase_email
  before_create :create_activation_digest

  scope :normal, -> {where admin: false}

  has_secure_password

  def digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
  end

  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def activate
    update_attributes activated: true
    update_attributes activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = self.new_token
    update_attributes reset_digest: self.digest(reset_token)
    update_attributes reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def current_lesson
    lessons.find_by(finished_time: nil)
  end

  def correct_words current_category
    self.lessons.select{|le| le.category_id == current_category.id }.map{|_| _.results.select{|re| re.word_answer.correct? }.map{ |r| r.word} }
  end

  def unlearned_words current_category
    current_category.words.reject{|ca| self.correct_words(current_category).first.include? ca }.map{|w| w }
  end

  def unlearned_words_not_in_the_lesson current_category, current_lesson
    current_category.words.reject{|ca| (self.correct_words(current_category).first.include? ca) || (current_lesson.results.map{|r| r.word}.include? ca) }.map{|w| w }
  end

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = self.new_token
    self.activation_digest = self.digest activation_token
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = User.order(:name).paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.activate
      flash[:success] = t ".success"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".success"
      if current_user == @user
        redirect_back_or admin_user_path @user
      else
        redirect_back_or admin_users_path
      end
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update]
  before_action :require_user
  before_action :correct_user, only: [:edit, :update]
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = User.normal.paginate page: params[:page]
  end

  def show
    @followers = @user.followers.paginate page: params[:page]
    @following = @user.following.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t ".info"
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def require_user
    if current_user.admin?
      flash[:warning] = t ".warning"
      redirect_to admin_user_path current_user
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end

  def find_user
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td align="center">
    <% if !current_user? user %>
      <%= link_to [:admin, user], method: :delete, data: {confirm: t(".confirm")} do %>
        <em class="glyphicon glyphicon-trash"></em>
      <% end %>
      &nbsp;
      <%= link_to edit_admin_user_path user do %>
        <em class="glyphicon glyphicon-edit"></em>
      <% end %>
    <% end %>
  </td>
  <td>
    <%= link_to admin_user_path user do %>
      <%= gravatar_for user, size: 40 %>
      <%= user.name %>
    <% end %>
  </td>
  <td>
    <%= user.email %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :title, t(".title") %>
<ul class="breadcrumb">
    <li><%= link_to t(".current_menu"), admin_users_path %></li>
    <li><%= link_to @user.name, admin_user_path(@user) %></li>
    <li class="active"><%= t ".current_action" %></li>
</ul>
<h1><%= t ".page_header" %></h1>
<div class="row">
  <div class="col-lg-8">
    <%= form_for [:admin, @user], html: {class: "margin-bottom-40"} do |f| %>
      <%= render "shared_pages/error_messages", object: f.object %>
      <div class = "form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :password_confirmation, t(".confirmation") %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit t(".save"), class: "btn btn-primary" %>
    <% end %>
    <br/>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t(".change"), "http://gravatar.com/emails", target: "_blank" %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<ul class="breadcrumb">
    <li><%= link_to t(".title"), admin_users_path %></li>
    <li class="active"><%= t ".current_action" %></li>
</ul>
<div class="panel panel-default panel-table">
  <div class="panel-heading">
    <div class="row">
      <div class="col col-xs-6">
        <h3 class="panel-title"><%= t ".title" %></h3>
      </div>
      <div class="col col-xs-6 text-right">
      <%= button_to "Create New", new_admin_user_path,
        class: "btn btn-sm btn-primary btn-create", method: "get" %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-bordered table-list">
      <thead>
        <tr>
          <th><em class="glyphicon glyphicon-cog"></em></th>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
        </tr>
      </thead>
      <tbody class="users">
        <%= render @users %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <%= will_paginate %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, t(".title") %>
<ul class="breadcrumb">
  <li><a href="#"><%= t ".current_menu" %></a></li>
  <li class="active"><%= t ".current_action" %></li>
</ul>
<strong> <h1> <%= t ".title" %> </h1> </strong>
<div class="row">
  <div class="col-lg-8">
    <%= form_for [:admin, @user], html: {class: "margin-bottom-40"} do |f| %>
      <%= render "shared_pages/error_messages", object: f.object %>
      <div class = "form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.check_box :admin %>
        <%= f.label "Administrator" %>
      </div>
      <div class = "form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :password_confirmation, t(".confirmation") %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit t(".create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% provide :title, @user.name %>
<ul class="breadcrumb">
    <li><%= link_to t(".current_menu"), admin_users_path %></li>
    <li class="active"><%= t ".current_action" %></li>
</ul>
<div class="row">
  <h1>
    <%= @user.name %>
  </h1>
</div>